company/urls.py
from django.urls import path
from . import views
from company.views import nightlife, reviews, DetailView, companyinfo, CompanyContactInfo, CompanyHours
app_name='company'
urlpatterns = [

    path('', views.index, name='index'),
    path('foodandbev/', views.foodandbev, name='foodandbev'),
    path('nightlife/', views.nightlife, name='nightlife'),
    path('entertainment/', views.entertainment, name='entertainment'),
    path('services/', views.services, name='services'),
    path('religious/', views.religious, name='religious'),
    path('products/', views.products, name='products'),
    path('reviews/<int:companyname_id>', views.reviews, name='reviews'),
    path('promotions/', views.promotions, name='promotions'),
    path('map/<int:companyname_id>/', views.map, name='map'),
    path('addreview/', views.add_review, name='addreview'),
    path('<int:pk>/', DetailView.as_view(), name= 'detail'),
    path('companycontactinfo_detail/(int:pk>', CompanyContactInfo.as_view(), name='companycontactinfo_detail'),
    path('companyhours_detail/<int:pk>', CompanyHours.as_view(), name= 'companyhours_detail'),
    path('company/<int:companyname_id>', views.companyname_detail, name='companyname_detail'),
    path('companyname/<int:companyname_id>/add_review/', views.add_review, name='add_review'),
    path('review/(<int:review_id>', views.review_detail, name='review_detail'),
    path('search/', views.search, name='search')
]

phonebook/urls.py
from django.contrib import admin
from django.urls import path, include
from company import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('company/', include('company.urls')),
    path('', views.index, name='index'),


]

company/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
import numpy as np

ONE_STAR = 'one star'
TWO_STARS = 'two stars'
THREE_STARS = 'three stars'
FOUR_STARS = 'four stars'
FIVE_STARS = 'five stars'
RATING_CHOICES = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
    )

FOOD_and_DRINKS = 'FOOD & DRINKS'
ENTERTAINMENT = 'ENTERTAINMENT'
SERVICES = 'SERVICES'
PRODUCTS = 'PRODUCTS'
RELIGIOUS_SERVICES = 'RELIGIOUS SERVICES'
NIGHTLIFE = 'NIGHTLIFE'
COMPANY_TYPE_CHOICES = (
    (FOOD_and_DRINKS, 'Food & Drinks'),
    (ENTERTAINMENT, 'Entertainment'),
    (SERVICES, 'Services'),
    (PRODUCTS, 'Products'),
    (RELIGIOUS_SERVICES, 'Religious Services'),
    (NIGHTLIFE, 'Nightlife'),
)
company_type = models.CharField(
    max_length=25,
    choices=COMPANY_TYPE_CHOICES,
    default=PRODUCTS,
)

class CompanyName(models.Model):
    companyname = models.CharField(max_length=50)
    company_type = models.CharField(choices=COMPANY_TYPE_CHOICES, max_length=25)
    description = models.TextField(max_length=500, null=True, blank=True)
    company_image = models.URLField(max_length=50, null=True, blank=True)


    def __str__(self):
        return self.companyname

    def get_absolute_url(self):
        return reverse('company:companyname-detail', kwargs={'pk': self.pk})


@receiver(post_save, sender=CompanyName)
def create_address(sender, **kwargs):
    if kwargs.get('created', False):
        CompanyAddress.objects.get_or_create(companyname=kwargs.get('instance'))
        CompanyContactInfo.objects.get_or_create(companyname=kwargs.get('instance'))
        CompanyHours.objects.get_or_create(companyname=kwargs.get('instance'))




class CompanyHours(models.Model):
    companyname = models.OneToOneField(CompanyName, related_name='name', on_delete=models.CASCADE)
    monday_open = models.TimeField(blank=True, null=True)
    tuesday_open = models.TimeField(blank=True, null=True)
    wednesday_open = models.TimeField(blank=True, null=True)
    thursday_open = models.TimeField(blank=True, null=True)
    friday_open = models.TimeField(blank=True, null=True)
    saturday_open = models.TimeField(blank=True, null=True)
    sunday_open = models.TimeField(blank=True, null=True)
    weekdays_open = models.TimeField(blank=True, null=True)
    weekend_open = models.TimeField(blank=True, null=True)
    weekend_close = models.TimeField(blank=True, null=True)
    weekdays_close = models.TimeField(blank=True, null=True)
    monday_close = models.TimeField(blank=True, null=True)
    tuesday_close = models.TimeField(blank=True, null=True)
    wednesday_close = models.TimeField(blank=True, null=True)
    thursay_close = models.TimeField(blank=True, null=True)
    friday_close = models.TimeField(blank=True, null=True)
    saturday_close = models.TimeField(blank=True, null=True)
    sunday_close = models.TimeField(blank=True, null=True)


    def get_absolute_url(self):
        return reverse('company:detail', kwargs={'pk': self.pk})
'''
    def check_time(time_to_check, open, closed):
        OPEN=1
        CLOSED=2
        if on_time > off_time:
            if time_to_check > on_time or time_to_check < off_time:
                return CLOSED, True
        elif on_time < off_time:
            if time_to_check > on_time and time_to_check < off_time:
                return OPEN, True
'''



class CompanyAddress(models.Model):
    companyname = models.OneToOneField(CompanyName, related_name='address', on_delete=models.CASCADE)
    street_address = models.CharField(blank=True, null=True, max_length=50)
    city = models.CharField(max_length=25, blank=True, null=True)
    state = models.CharField(max_length=2, blank=True, null=True)
    zipcode = models.IntegerField(null=True)
    longitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)
    latitude = models.DecimalField(max_digits=9, decimal_places=6, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('company:map', kwargs={'pk': self.pk})



class CompanyContactInfo(models.Model):
    companyname = models.OneToOneField(CompanyName, related_name='contact', on_delete=models.CASCADE)
    phone = models.CharField(max_length=14, blank=True, null=True)
    first_name = models.CharField(max_length=25, blank=True, null=True)
    last_name = models.CharField(max_length=25, blank=True, null=True)
    email = models.EmailField(max_length=35, blank=True, null=True)
    company_image = models.URLField(max_length=50, null=True, blank=True)
    website = models.URLField(max_length=50, blank=True, null=True)
    facebook = models.URLField(max_length=100, blank=True, null=True)
    instagram = models.URLField(max_length=50, blank=True, null=True)
    twitter = models.URLField(max_length=50, blank=True, null=True)
    pintrest = models.URLField(max_length=50, blank=True, null=True)

    def get_absolute_url(self):
        return reverse('company:companycontactinfo_detail', kwargs={'pk': self.pk})



class Review(models.Model):
    ONE_STAR = 'one star'
    TWO_STARS = 'two stars'
    THREE_STARS = 'three stars'
    FOUR_STARS = 'four stars'
    FIVE_STARS = 'five stars'
    RATING_CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )

    FOOD_and_DRINKS = 'FOOD & DRINKS'
    ENTERTAINMENT = 'ENTERTAINMENT'
    SERVICES = 'SERVICES'
    PRODUCTS = 'PRODUCTS'
    RELIGIOUS_SERVICES = 'RELIGIOUS SERVICES'
    OTHER = 'OTHER'
    COMPANY_TYPE_CHOICES = (
        (FOOD_and_DRINKS, 'Food & Drinks'),
        (ENTERTAINMENT, 'Entertainment'),
        (SERVICES, 'Services'),
        (PRODUCTS, 'Products'),
        (RELIGIOUS_SERVICES, 'Religious Services'),
        (OTHER, 'Other'),
    )
    companyname = models.ForeignKey(CompanyName, related_name='review', on_delete=models.CASCADE)
    company_type = models.CharField(choices=COMPANY_TYPE_CHOICES, max_length=25)
    first_name = models.CharField(blank=True, max_length=50)
    last_name = models.CharField(blank=True, max_length=25)
    comment = models.TextField(blank=True, max_length=500)
    rating = models.IntegerField(choices=RATING_CHOICES)
    pub_date =  models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('company:review_detail.html', kwargs={'pk':self.pk})

    @classmethod
    def avg(some):
        tot=0
        for q in some:
            tot=tot+q
        zavg=tot/len(some)
        return zavg

    def __str___(self):
        return self.companyname

templates/company_list.html
<!DOCTYPE html>

{% load widget_tweaks %}
{% load static %}
<html lang="en">

<head runat="server">
   <title>Mobile first sample page</title>
   <meta name="viewport" content="width=device-width,
      initial-scale=1" />
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link href="{% static 'company/bootstrap-social.css' %}"  rel="stylesheet" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="{% static 'company/styles.css' %}" rel="stylesheet" />
</head>
<body>
<style>
body {
  background-image: linear-gradient(to left bottom, #051937, #004d7a, #008793, #00bf72, #a8eb12);

}
.grid-container {
  display: grid;
  width: 360px;
  height: 100%;
  grid-template-columns: 80px 280px;
  grid-template-rows: 115px 115px 115px 115px 115px;
  grid-gap: 2px 1px;
  grid-template-areas: "image company" "image1 company1" "image2 company2" "image3 company3" "image4 company4";
}
.image { grid-area: image;
  border-width: 2px;
  border-color: black;
  border-style: solid;
  height: 100px;
width: 100px;

}

.company { grid-area: company;
  color: white;
  padding-right: 10px;
padding-left: 5px;
padding-bottom: 15px;
width:275px;
border-left: 0px;
border-width: 3px;
border-color: white;
border-style: solid;
height: 110px;
margin-left: 20px;
height: 102px;
text-align: center;
}
.companydescription { grid-area: company;
  font-size: 10px;
  text-align: left;
  padding-left: 5px;
}

a {
  color: white;
}
  .button {
    width: 85px;
    height: 40px;
    margin-right: 145px;
    margin-left: 20px;
    margin-bottom: 15px;
    margin-top: 10px;
    color: white;
    border-style: solid;
    border-width: 3px;
    border-color: white;
    background-color: #051937;
  }

  .backbutton {
    color: white;
      width: 85px;
      margin-top: 10px;
      height: 40px;
     margin-bottom: 15px;
     border-style: solid;
     border-width: 3px;
     border-color: white;
     background-color: #051937;
    }
img {
  width:100px;
 height: 100px;
 }
 .formcontainer {
   width:375px;
   height: 175px;
   margin-top: 10px;
 }
 .submit {
   color:white;
   font-size: 18px;
   margin-left: 250px;
  border-style: solid;
  border-width: 3px;
  border-color: white;
  background-color: #051937;
  padding-bottom: 10px;
 }
 .form-control {
   width:200px;
   font-size: 18px;
   margin-left: 25px;
   border-style: solid;
   border-width: 2px;
   border-color: black;
   margin-top: 10px;
   padding-bottom: 10px;
 }
 label {
   font-size: 18px!important;
   margin-left: 5px;
   color: white;
   margin-bottom: 10px;
   margin-right: 10px;
 }
 input {
   width: 200px;
   background-color: white;
   margin-left: 50px;

  }
#id_company_type {
  background-color: white;
  margin-top: 15px;

}
.container {
width: 375px;
border-style: solid;
border-width: 3px;
border-color: white;
}
.results {
  margin-top: 35px;
  text-align: left;
  font-size: 18px;
  margin-left: 10px;
}
.nav {
  width: 375px;
}
</style>

   <body>
<nav class='nav'>
  <a class='btn-primary btn button' href="/">Back
  </a>
  <a class='btn-primary btn backbutton' href="/company/search/">Search
  </a>
</nav>

<div class='formcontainer'>
  <div class= 'container'>
  <form method="get">
  {{ filter.form.as_table }}
    <button class='submit' type="submit">Search</button>
  </form>
</div>
</div>

  {% for companyname in filter.qs %}
     <div class="grid-container">

       <div class="image">
         <img src='{{companyname.company_image}}'>
       </div>




       <div class="company">
         <div class='results'>
         {{ companyname.companyname }} -  <a href='/company/{{companyname.pk}}'>more inof...</a>
</div>
       </div>
{% endfor %}

  </body>

templates/companyinfo.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head runat="server">
   <title>Mobile first sample page</title>
   <meta name="viewport" content="width=device-width,
      initial-scale=1" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="{% static 'company/styles.css' %}" rel="stylesheet" />
</head>

<style>


.grid-container {
  display: grid;
  height: 100%;
  grid-template-columns: 180px 180px;
  grid-template-rows: 75px 75px 200px 200px 110px;
  grid-gap: 0px;
  grid-template-areas: "nav nav" "businessname businessname" "image image" "businesshours businesshours" "icons icons";
}
.nav{ grid-area: nav;
  width: 100%;
  height:75px;
}
.searchbutton {
  width: 70px;
  margin-left: 30px;
  height: 30px;
  margin-top: 20px;
}
.backbutton {
    width: 70px;
    margin-left: 165px;
    height: 30px;
    margin-top: 20px;
  }
.businessname{ grid-area: businessname;
width: 340px;
height: 50px;
text-align: center;
background-color: ;
margin-left: 15px;
align-content: center;
font-size: 25px;
padding-top: 5px;
border-width: 2px;
border-color: lightgray;
border-style: solid;}

.image{ grid-area: image;
  width: 375px;
  height: 200px;
}


.businesshours { grid-area: businesshours;
height: 200px;
width: 375px;
background-color: green;}

.icons { grid-area: icons;
  background-color: gray;
  width: 375px;
  height: 110px;

  padding-top: 10px;
  color: white;
}
.btn-facebook {
  margin-top: 10px;
  width: 70px;
  height: 65px;
  margin-right: 15px;
  margin-left: 15px;
  text-align: center;
}
.btn-twitter{
  width: 70px;
  height: 65px;
  margin-top: 10px;
  margin-right: 15px;
  text-align: center;
}
.btn-instagram {
  width: 70px;
  height: 65px;
  margin-top: 10px;
  margin-right:15px;
  text-align: center;
}
.btn-pinterest {
  width: 70px;
  height: 65px;
  text-align: center;
  margin-top:10px;
  margin-right: 10px;

}

</style>
<body>
  <div class="grid-container">
  <div class="nav">
    <div class='navbuttons'>
    <a class='btn-primary btn searchbutton' href="{% url 'company:companyinfo'%}">Back
    </a>
    <a class='btn-primary btn backbutton' href="{% url 'company:index'%}">Search
    </a>
  </div>
</div>

<div class='businessname'>
<p>{{object.companyname}}</p>
</div>
  <div class="image">
    <img src='https://picsum.photos/375/200image=0' alt='business picture'>
</div>
    <div class="businesshours">
     </div>
     <div class="icons">
       <a class="btn btn-social-icon btn-facebook" href='{{object.facebook}}'>Facebook

  </a>
   <a class="btn btn-social-icon btn-twitter" href='{{object.twitter}}'>  Twitter
    </a>
    <a class="btn btn-social-icon btn-instagram" href='{{object.instagram}}'>Instagram
     </a>
     <a class="btn btn-social-icon btn-pinterest" href='{{object.pintrest}}'>Pinterest
      </a>
     </div>
   </div>

</body>
<script>
     src="https://code.jquery.com/jquery-2.1.1.min.js"
     integrity="sha256-h0cGsrExGgcZtSZ/fRz4AwV+Nn6Urh/3v3jFRQ0w9dQ="
     crossorigin="anonymous">
</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

templates/companyname_detail.html
{% load bootstrap3 %}
<h2>{{ companyname.companyname }}</h2>



<h3>Recent reviews</h3>

{% if companyname.review_set.all %}
<div class="row">
    {% for review in review_set.all %}
    <div class="col-xs-6 col-lg-4">
        <em>{{ review.comment }}</em>
        <h6>Rated {{ review.rating }} of 5 by <a href="{% url 'reviews:user_review_list' review.user_name %}" >{{ review.user_name }}</a></h6>
        <h5><a href="{% url 'reviews:review_detail' review.id %}">
        Read more
        </a></h5>
    </div>
{% endfor %}
</div>
{% else %}
<p>No reviews for this wine yet</p>
{% endif %}

<h3>Add your review</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'company:add_review' companyname.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}
</form>

templates/companyreviews.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head runat="server">
   <title>Mobile first sample page</title>
   <meta name="viewport" content="width=device-width,
      initial-scale=1" />
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
      <link href="{% static 'company/bootstrap-social.css' %}"  rel="stylesheet" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="{% static 'company/styles.css' %}" rel="stylesheet" />
</head>
<body>
<style>
.grid-container {
  display: grid;
  height: 100%;
  grid-template-columns: 180px 180px;
  grid-template-rows: 75px 100px 330px 120px;
  grid-gap: 0px;
  grid-template-areas: "nav nav" "average average" "reviews reviews" "icons icons";
}

.nav{ grid-area: nav;
  width: 375px;
  height:75px;
  background-image: linear-gradient(to right top, #eceee6, #a9b1ad, #6f7778, #3d4144, #111014);}


.searchbutton {
  width: 70px;
  margin-left: 30px;
  height: 30px;
  margin-top: 20px;
}
.backbutton {
    width: 70px;
    margin-left: 165px;
    height: 30px;
    margin-top: 20px;
  }
.average { grid-area: average;
  width: 375px;
  border-color: black;
  border-style: solid;
  border-width: 2px;
  background-color: lightgray;
}

.reviews { grid-area: reviews;
  width: 375px;
  border-color: black;
  border-style: solid;
  border-width: 2px;
  background-image: linear-gradient(to right top, #eceee6, #a9b1ad, #6f7778, #3d4144, #111014);
}

.icons { grid-area: icons;
width: 375px;
border-color: lightgray;
border-style: solid;
border-width: 2px;
background-image: linear-gradient(to right top, #eceee6, #a9b1ad, #6f7778, #3d4144, #111014);
}
.contactbutton {
  margin-top: 10px;
  width: 85px;
  height: 85px;
  margin-left: 10px;
  padding-top: 20px;
  text-align: center;
}
.searchpage {
  width: 85px;
  height: 85px;
  margin-top: 10px;
  padding-top: 10px;
  text-align: center;
}
.promosbutton {
  width: 85px;
  height: 85px;
  margin-top: 10px;
  padding-top: 20px;

  text-align: center;
}
.mapbutton {
  width: 85px;
  height: 85px;
  text-align: center;
  margin-top:10px;
    padding-top: 20px
}

</style>

   <body>
     <div class="grid-container">
       <div class="nav">
         <div class='navbuttons'>
         <a class='btn-primary btn searchbutton' href="{% url 'company:companyinfo'%}">Back
         </a>
         <a class='btn-primary btn backbutton' href="{% url 'company:index'%}">Search
         </a>
       </div>
     </div>
{% for x in companyname %}
       <div class="average">
{{x.companyname}}

       </div>
       {% endfor %}
       <div class="reviews">
       </div>
       <div class="icons">

       <a class="btn-primary contactbutton btn"  href= "#">Conact<br/>Infor
         </a>
          <a class="btn-primary btn searchpage" href='{{object.twitter}}'>Search<br/>for a<br/>Business
           </a>
           <a class="btn-primary btn promosbutton" href='{{object.instagram}}'>Promo<br/>Codes
            </a>
            <a class="btn-primary mapbutton btn" href='{{object.pintrest}}'>Get<br/>Directions
             </a>
            </div>
     </div>


  </body>
   <script
   			  src="https://code.jquery.com/jquery-2.1.1.min.js"
   			  integrity="sha256-h0cGsrExGgcZtSZ/fRz4AwV+Nn6Urh/3v3jFRQ0w9dQ="
   			  crossorigin="anonymous">
  </script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head runat="server">
   <title>Mobile first sample page</title>
   <meta name="viewport" content="width=device-width,
      initial-scale=1" />
   <link href="{%static 'bootstrap.min.css' %}" rel="stylesheet" />
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="{% static 'styles.css' %}" rel="stylesheet" />
</head>
<body>
<style>
body {
  width: 375px!important;
  height: 700px;

background-image: linear-gradient(to left bottom, #051937, #004d7a, #008793, #00bf72, #a8eb12);
}
.extraClass {
  font-size: 90px;
  height: 110px;
  width: 115px;
  margin-top: 15px;
  margin-bottom: 15px;
  color:  #009efa;
}
.icon-bar {
margin-top: 5px;

}
#navbarContent {
height: 170px;
width: 350px;
padding-left: 10px;
margin-top: 15px;
grid-template-areas: "image company" "image1 company1" "image2 company2" "image3 company3" "image4 company4";
}

.main-container {

  padding-top: 5px;
  grid-template-areas: "image company" "image1 company1" "image2 company2" "image3 company3" "image4 company4";


}
.icon-detail {
  color: white;
  width: 350px;
  font-size: 22px;
  height: 25px;
  grid-template-areas: "image company" "image1 company1" "image2 company2" "image3 company3" "image4 company4";
  padding-left: 10px;
}
button {
background-image: linear-gradient(to right top, #051937, #004d7a, #008793, #00bf72, #a8eb12);
  margin-left: 20px;
  padding-left: 10px;
  padding-right: 10px;
}
</style>
   <div id="divContainer" class="main-container">
            <div id="navbarContent">

              <a  href= "{% url 'company:foodandbev' %}">   <button type="button"> <span class="icon-bar"><i class="fa fa-utensils extraClass"></i></span>

            </button>  </a>
                <button type="button"
                     <span class="icon-bar"><i  class="fa fa-cocktail extraClass"></i></span>
                     <a href="{% url 'company:foodandbev' %}">
                   </button>
                 </div>

                <div id="divContainer" class="icon-detail">  &nbsp
                <a href= "{% url 'company:foodandbev' %}">Resturants</a> &nbsp &nbsp&nbsp &nbsp</a><a href="{% url 'company:foodandbev' %}">Night Life</a>
                </div>
                <div id="divContainer" class="main-container">
                         <div id="navbarContent">
                    <button type="button"
                    <span class="icon-bar"><i class="fa fa-film extraClass"></i></span>
                  </button>
                    <button type="button"
                    <span class="icon-bar"><i class="fa fa-shopping-cart extraClass"></i></span>
                    </button>
</div>
<div id="divContainer" class="icon-detail">&nbsp &nbsp
  <a href= "{% url 'company:foodandbev' %}">Leisure</a> &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp</a><a href="{% url 'company:foodandbev' %}">Products</a></div>
<div id="divContainer" class="main-container">
         <div id="navbarContent">

                    <button type="button"
                    <span class="icon-bar"><i class="fa fa-balance-scale extraClass"></i></span>
                 </button>
                 <button type="button"
                   <span class="icon-bar"><i class="fa fa-church extraClass"></i></span>
                 </button>
            </div>
            <div id="divContainer" class="icon-detail"> &nbsp  &nbsp
  <a href= "{% url 'company:foodandbev' %}">Services</a> &nbsp &nbsp&nbsp &nbsp &nbsp &nbsp</a><a href="{% url 'company:foodandbev' %}">Religious</a>            </div>

         </div>
       </div>
 </div>
    </body>
   <script
   			  src="https://code.jquery.com/jquery-2.1.1.min.js"
   			  integrity="sha256-h0cGsrExGgcZtSZ/fRz4AwV+Nn6Urh/3v3jFRQ0w9dQ="
   			  crossorigin="anonymous">
  </script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>